In [3]:
import numpy as np

In [6]:
A = np.random.random((3,3))

In [7]:
A

array([[0.51057346, 0.02641371, 0.11369526],
       [0.8587529 , 0.84233035, 0.62184659],
       [0.95141663, 0.69563763, 0.37927016]])

In [8]:
A

array([[0.51057346, 0.02641371, 0.11369526],
       [0.8587529 , 0.84233035, 0.62184659],
       [0.95141663, 0.69563763, 0.37927016]])

In [9]:
A < 5

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
A >5

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [11]:
type(A)

numpy.ndarray

In [12]:
A.dtype

dtype('float64')